/** This file is automatically generated by src/ipc/generateIpcRegistrationScript.ts
*  Manual modifications will be overwritten.
*/
// needs to match the type being used by the underlying system
/* eslint-disable @typescript-eslint/no-explicit-any */
// linter seeing all of the extracted variables as unused
/* eslint-disable @typescript-eslint/no-unused-vars */
import editData from '../ipc/editData/editData';
import getData from '../ipc/getData/getData';
import pickFile from '../ipc/pickFile/pickFile';
import resetDatabase from '../ipc/resetDatabase/resetDatabase';

export {};
const [editDataEvent, ...editDataRest] = Parameters(typeof editData);
const [getDataEvent, ...getDataRest] = Parameters(typeof getData);
const [pickFileEvent, ...pickFileRest] = Parameters(typeof pickFile);
const [resetDatabaseEvent, ...resetDatabaseRest] = Parameters(typeof resetDatabase);

declare global {
  interface Window {
    electronAPI: {
      editData: (...editDataRest)=>ReturnType<editData>,
      getData: (...getDataRest)=>ReturnType<getData>,
      onDataUpdated: (callback: (event: Event, data: SetStateAction<any[]>)=>void)=>void,
      pickFile: (...pickFileRest)=>ReturnType<pickFile>,
      resetDatabase: (...resetDatabaseRest)=>ReturnType<resetDatabase>,

    }
  }
}
