import React from 'react';

import Head from 'next/head';

import SecondaryView from '../views/SecondaryView';

export default function Home() {
  return (
    <>
      <Head>
        <title>Secondary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SecondaryView />
    </>
  );
}
