import {
  BrowserWindow,
} from 'electron';

import backendRegistrationScript from '../../../ipc/backendRegistrationScript';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const STORYBOOK_URL = 'http://localhost:6006';

// manually putting in due to electronegativity issues seeing otherwise
// const webPreferences = {
//   preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
//   disableBlinkFeatures: 'Auxclick',
//   contextIsolation: true,
//   sandbox: true,
// };

function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      // make sure that there is nothing dangerous in the preload scripts
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, /* eng-disable PRELOAD_JS_CHECK */
      disableBlinkFeatures: 'Auxclick',
      contextIsolation: true,
      sandbox: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  backendRegistrationScript({
    window: mainWindow,
  });

  if (process.env.INCLUDE_STORYBOOK_WINDOW === 'true') {
    // Create the browser window.
    const storybookWindow = new BrowserWindow({
      height: 600,
      width: 800,
      x: 0,
      y: 0,
      webPreferences: {
        // make sure that there is nothing dangerous in the preload scripts
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, /* eng-disable PRELOAD_JS_CHECK */
        disableBlinkFeatures: 'Auxclick',
        contextIsolation: true,
        sandbox: true,
      },
    });

    // and load the index.html of the app.
    storybookWindow.loadURL(STORYBOOK_URL);
    // Open the DevTools.
    storybookWindow.webContents.openDevTools();

    backendRegistrationScript({
      window: storybookWindow,
    });
  }
}

export default createWindow;
