/** This file is automatically generated by src/ipc/generateIpcRegistrationScript.ts
*  Manual modifications will be overwritten.
*/
// logging warnings if something doesn't work so that they are seen
/* eslint-disable no-console */
import { BrowserWindow } from 'electron';
import BaseBackendRegistrationParameterType from './BaseBackendRegistrationParameter.type';
import editDataBackendRegistration from './editData/editData.backendRegistration';
import getDataBackendRegistration from './getData/getData.backendRegistration';
import pickFileBackendRegistration from './pickFile/pickFile.backendRegistration';
import resetDatabaseBackendRegistration from './resetDatabase/resetDatabase.backendRegistration';

let registrationCalledCount = 0;
const windows: BrowserWindow[] = [];

function backendRegistrationGeneration({ window }: BaseBackendRegistrationParameterType) {
  windows.push(window);
  registrationCalledCount += 1;
  if (registrationCalledCount > 1) {
    return;
  }

  try {
    editDataBackendRegistration();
  } catch (e) {
    console.warn('registration failed', e.message);
  }
  try {
    getDataBackendRegistration();
  } catch (e) {
    console.warn('registration failed', e.message);
  }
  try {
    pickFileBackendRegistration({ windows });
  } catch (e) {
    console.warn('registration failed', e.message);
  }
  try {
    resetDatabaseBackendRegistration({ windows });
  } catch (e) {
    console.warn('registration failed', e.message);
  }
}
export default backendRegistrationGeneration;
