version: '3.1'

services:

  nest:
    image: node:18-alpine
    volumes:
      - './:/code'
    working_dir: /code
    user: node
    command:
      - sh
      - -c
      - |
        npm install
        npm run start
    ports:
      - "3000:3000"
    # environment:
    #   - DATABASE_URL=sqlserver://sqlServer:1433;database=Default;user=SA;password=PasswordsR0ck!;encrypt=true;trustServerCertificate=true
    #   - REDIS_CONNECTION_STRING=redis://redis:6379

  
  # Microsoft SQL Server
  # sqlServer:
  #   image: 'azure-sql-edge:latest'
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Pa$$wordsR0ck
  #   ports:
  #     - "1433:1433"


  # Redis Server
  # redis:
    # image: redis/redis-stack
    # ports:
    #   - "6379:6379"
    #   - "8001:8001"